name: DevOps Kit CI

on:
  push:
    branches:
      - main
      - "feature/**"
      - "patch/**"
      - "hotfix/**"
      - "dependabot/**"
  pull_request:
    branches:
      - main

jobs:
  versioning:
    name: Semantic Versioning
    uses: ./.github/workflows/semver-create.yml

  tagging:
    name: Git Tagging
    needs: versioning
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/semver-tag.yml
    permissions:
      contents: write
    with:
      version: ${{ needs.versioning.outputs.version }}
